### ISSUE TITLE
Improve Locales section

### ISSUE THREAD

**Issue by brunoocasali** [internetsistemas/guides#29]
If we change a little our default's we can improve a lot the implementation of the localization standards:

``` yml
# from this:
pt-BR:
  views:
    admin:
      users:
         index:
           title: Usuários
         new:
            title: Novo Usuário
            form:
              legend:
                remuneration: Remuneração

         edit:
           title: Editar Usuário


# to this:
pt-BR:
  admin:
    users:
      index:
        title: Usuários

      new:
        title: Novo Usuário

      edit:
        title: Editar Usuário

      form:
        legend:
          remuneration: Remuneração
```

``` slim
# app/views/admin/users/new.html.slim
​
# and our implementation will be:
.content.new-user
  .header
    .row
      .large-12.columns
        h3.title = t '.title'
​
# instead of:
.content.new-user
  .header
    .row
      .large-12.columns
        h3.title = t 'views.admin.users.new.title'
```
